## 1.线程安全

### 1-1.什么是线程安全问题

> <<Java Concurrency In Practice>>的作者对线程安全问题下了一个定义: 当多线程访问一个对象时, 如果不考虑这些线程的调度和交替执行, 也不需要额外的同步, 都能得到正确的结果, 那么这个对象就是线程安全的.

### 1-2.为什么会出现线程安全问题

#### 1-2-1.竞争产生的结果错误

```java
// 当我们两个线程都做++ 操作时,得到的结果不是我们想要20000
public class AddThread implements Runnable{
    private static int index = 0;

    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            index++;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Runnable runnable = new AddThread();
        Thread threadA = new Thread(runnable);
        threadA.start();

        Thread threadB = new Thread(runnable);
        threadB.start();

        threadA.join();
        threadB.join();
        System.out.println(index);
    }
}

// 运行结果
18351
```



#### 1-2-2.活跃性问题(死锁, 活锁, 饥饿)

```java
public class DeadLock implements Runnable {

    // 创建两把锁并重写tostring, 方便测试
    private Object lock1 = new Object(){
        @Override
        public String toString() {
            return "lock1";
        }
    };
    private Object lock2 = new Object() {
        @Override
        public String toString() {
            return "lock2";
        }
    };
    Map<Integer, Object> map = new HashMap<>();

    @Override
    public void run() {
        synchronized (map.get(1)) {
            System.out.println(Thread.currentThread().getName() + "获取到" + map.get(1).toString());
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            synchronized (map.get(2)) {
                System.out.println(Thread.currentThread().getName() + "获取到" + map.get(2).toString());
            }
        }
    }

    public static void main(String[] args) {
        DeadLock runnable1 = new DeadLock();
        runnable1.map.put(1, runnable1.lock1);
        runnable1.map.put(2, runnable1.lock2);

        DeadLock runnable2 = new DeadLock();
        runnable2.map.put(1, runnable1.lock2);
        runnable2.map.put(2, runnable1.lock1);

        new Thread(runnable1).start();
        new Thread(runnable2).start();
    }
}
```



#### 1-2-3.发布对象&&对象初始化安全问题

- 发布: 比如我们的把一个成员定义为public, 或者将对象return, 或者当做参数传递这些都是发布

- 溢出: 对象发布到了不该发布的地方:

- > 1.方法返回了一个private的对象
  >
  > ```java
  > public class ObjectOver1 {
  > 
  >     private HashMap<Integer, String> map;
  > 
  >     public ObjectOver1() {
  >         this.map = new HashMap<>();
  >         map.put(1, "1");
  >         map.put(2, "2");
  >         map.put(3, "3");
  >     }
  > 
  >     public HashMap<Integer, String> getMap() {
  >         return map;
  >     }
  > 
  >     public static void main(String[] args) {
  >         ObjectOver1 instance = new ObjectOver1();
  >         instance.getMap().remove(1);
  >         System.out.println(instance.getMap().toString());
  >     }
  > }
  > 
  > // 运行结果
  > {2=2, 3=3}
  > 
  > // 避免溢出, 我们返回private对象的时候返回一个新对象
  > public HashMap<Integer, String> getMap<>() {
  >   return new HashMap(map);
  > }
  > ```
  >
  > 2.还没有完成初始化就this赋值. this被赋值给另外一个对象
  >
  > 3.在构造函数中新建线程
  >
  > ```java
  > public class ObjectOver1 {
  > 
  >     private HashMap<Integer, String> map;
  > 
  >     public ObjectOver1() {
  >         new Thread(() -> {
  >             this.map = new HashMap<>();
  >             map.put(1, "1");
  >             map.put(2, "2");
  >             map.put(3, "3");
  >         });
  >     }
  > 
  >     public HashMap<Integer, String> getMap() {
  >         return map;
  >     }
  > 
  >     public static void main(String[] args) {
  >         ObjectOver1 instance = new ObjectOver1();
  >         instance.getMap().remove(1);
  >         System.out.println(instance.getMap().toString());
  >     }
  > }
  > 
  > // 运行结果
  > Exception in thread "main" java.lang.NullPointerException
  > 	at com.polar.concurrence.thread.ObjectOver1.main(ObjectOver1.java:26)
  > ```